server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha

clients:
  rates:
    base-url: http://localhost:8089
    connect-timeout-ms: 1000
    read-timeout-ms: 1500
